Добавлено описание и схема БД
KraynovAlexander/java-filmorate pull request #3
Opened 2022-06-13 14:32 UTC by KraynovAlexander

Задание 10 !

2022-06-13 14:35 UTC, sergey-oreshkin approved these changes
единственное замечание - два поля **film_id** в талице **films**
остальное нормально

2022-06-13 14:37 UTC, sergey-oreshkin requested changes
а нет. еще не хватает первичных ключей во всех таблицах

2022-06-13 20:29 UTC, KraynovAlexander commented
Так?

2022-06-14 04:52 UTC, sergey-oreshkin requested changes
первичные ключи должны быть уникальными и однозначно идентифицировать запись
а сейчас получается например в таблице **film_genres** может быть много записей с один и тем же _film_id_
в сводных таблицах этого можно достичь если использовать составные первичные  ключи, состоящие сразу из двух полей. для этого пометь оба поля что это первичный ключ

2022-06-14 09:37 UTC, NinaShch approved these changes
Вроде все супер, только насколько я помню у описания фильма 200 символов, а не 150

2022-06-14 18:26 UTC, sergey-oreshkin approved these changes
все ок

2022-06-24 17:18 UTC, avfyodorov reviewed
Замечание всего одно, а так всё очень хорошо.

2022-06-24 17:18 UTC, avfyodorov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                jdbcTemplate.update("INSERT INTO FILM_GENRES (film_id, genre_id) VALUES (?, ?)",
Это не очень удачное решение-прямой доступ к чужой таблице. По идее, данный класс должен работать только и исключительно со своей таблицей. Лучше было бы выделить методы изменения таблицы "Фильмы-Жанры" в отдельный класс.

модификация данных в таблице должны происходить исключительно и только в соответствующем классе. 
Принцип такой: одна таблица- один класс для добавления, удаления, изменения данных в этой таблице.

2022-06-26 18:53 UTC, avfyodorov reviewed
Добрый день!

Замечаний нет.
Работа принята.

2022-06-26 20:15 UTC, merged